import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./reset.css";
import "./globals.css";
import "flowbite/dist/flowbite.css";
import FooterComponent from "../components/footer";

const kanit = Kanit({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-400  flex justify-center ${kanit.className}`}>
        <main>{children}</main>
        <FooterComponent />
      </body>
    </html>
  );
}
